//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VacanciesViewer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacancy
    {
        public int Id { get; set; }
        public string title { get; set; }
        public string salary { get; set; }
        public string employer { get; set; }
        public string url { get; set; }
        public string requirement { get; set; }
        public string responsibility { get; set; }
        public string address { get; set; }
    }
}
